import subprocess
import os
import sys
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

SQL_CLI_PFX = """
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON;
SET ECHO OFF;
SET FEEDBACK OFF;
"""
SQL_CLI_SFX = "\nEXIT;"
VALID_SUFFIXES = {".sql", ".plsql", ".tbl", ".pkg", ".prc", ".fnc", ".trg", ".alter"}

def connection_string(pgdb: str = "QBL", is_admin: bool = False, as_sysdba: bool = False) -> str:
    env_usr = f"oracle_{pgdb}_user".upper()
    env_pwd = f"oracle_{pgdb}_pwd".upper()
    if is_admin:
        env_usr = f"oracle_{pgdb}pdb_admin_user".upper()
        env_pwd = f"oracle_{pgdb}pdb_admin_pwd".upper()
        
    env_host = f"oracle_{pgdb}_host".upper()
    env_port = f"oracle_{pgdb}_port".upper()
    env_service = f"oracle_{pgdb}_service".upper()

    db_user = os.getenv(env_usr)
    db_pwd = os.getenv(env_pwd)
    if not db_user or not db_pwd:
        raise EnvironmentError(f"Missing required environment variables: {env_usr} and/or {env_pwd}")

    db_host = os.getenv(env_host, "localhost")
    db_pdb = os.getenv(env_service, "QBLPDB")
    db_port = os.getenv(env_port, "1521")

    conn_str = f"{db_user}/\"{db_pwd}\"@//{db_host}:{db_port}/{db_pdb}"
    if as_sysdba:
        conn_str += " AS SYSDBA"
    return conn_str

def get_sql(file_path: str | Path) -> str:
    path_obj = Path(file_path)
    if not path_obj.exists():
        logger.error("File not found: %s", path_obj)
        sys.exit(1)
        
    return path_obj.read_text(encoding="utf-8")

def get_file_map(root_dir: str | Path) -> dict[str, str]:
    path_obj: Path = Path(root_dir)
    file_map: dict[str, str] = {}
    for file in path_obj.rglob("*"):
        if file.is_file() and file.suffix.lower() in VALID_SUFFIXES:
            file_map[file.name] = str(file.resolve())
    return file_map

def sort_file_map(file_map: dict[str, str]) -> list[tuple[str, str]]:
    return sorted(file_map.items(), key=lambda item: item[0])

def sql_runner(
    raw_sql: str, 
    conn_str: str
) -> subprocess.CompletedProcess:
            
    safe_sql = f"{SQL_CLI_PFX}{raw_sql}{SQL_CLI_SFX}"
    command = ["sqlplus", "-s", conn_str]
    
    return subprocess.run(
        command, 
        input=safe_sql, 
        check=False,
        text=True, 
        capture_output=True
    )

def create_db_logger(conn_str: str) -> None:
    raw_sql = """
    BEGIN
       EXECUTE IMMEDIATE 'CREATE TABLE DB_LOGGER (
           log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           schema_name VARCHAR2(128),
           file_name VARCHAR2(320),
           full_path VARCHAR2(3000),
           exec_status VARCHAR2(20) DEFAULT null,
           result CLOB,
           exec_at TIMESTAMP DEFAULT SYSTIMESTAMP
       )';
    EXCEPTION
       WHEN OTHERS THEN
          IF SQLCODE != -955 THEN
             RAISE;
          END IF;
    END;
    """
    result = sql_runner(raw_sql, conn_str)
    stdout_upper = result.stdout.upper()
    
    if result.returncode != 0 or "ORA-" in stdout_upper or "SP2-" in stdout_upper:
        logger.error("DB_LOGGER creation failed:\n%s", result.stdout.strip())
        sys.exit(1)

def insert_loop(conn_str: str, sorted_files: list[tuple[str, str]]) -> None:
    for file_name, file_path in sorted_files:
        raw_sql = get_sql(file_path)
        ext = Path(file_path).suffix.lower().strip(".")
        
        result = sql_runner(raw_sql, conn_str)
        
        stdout_upper = result.stdout.upper()
        status = "success".upper()
        output_msg = ""
        
        if result.returncode != 0 or "ORA-" in stdout_upper or "SP2-" in stdout_upper:
            status = "error".upper()
            output_msg = result.stdout.strip().replace("'", "''") 
            logger.error("SQL execution failed in %s:\n%s", file_name, result.stdout.strip())
        else:
            output_msg = result.stdout.strip().replace("'", "''")

        log_sql = f"""
        BEGIN
           INSERT INTO DB_LOGGER (schema_name, file_name, full_path, exec_status, result)
           VALUES (SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'), '{file_name}', '{file_path}', '{status}', '{output_msg[:3900]}');
           COMMIT;
        END;
        """
        sql_runner(log_sql, conn_str)
        
        if status == "error":
            sys.exit(1)

def build_db(root_dir: str | Path, pgdb: str = "QBL", is_admin: bool = False, as_sysdba: bool = False) -> None:
    conn_str = connection_string(pgdb, is_admin, as_sysdba)
    
    create_db_logger(conn_str)
    
    file_map = get_file_map(root_dir)
    sorted_files = sort_file_map(file_map)
    insert_loop(conn_str, sorted_files)
    