#!/usr/bin/env bash
# setup_nft_port_forward_service.sh
# Ubuntu: create a systemd service that sets up kernel-level (nftables) port forwarding (DNAT + optional MASQUERADE).
#
# Usage:
#   sudo ./setup_nft_port_forward_service.sh <listen_port> <target_host> <target_port> [proto] [listen_addr] [masq] [redirect_local_output]
#
# Defaults:
#   proto=tcp
#   listen_addr=0.0.0.0   (any destination address on this box)
#   masq=1                (SNAT/masquerade for forwarded connections; recommended for target on another host)
#   redirect_local_output=1 (also redirect connections *originating on this machine* to listen_port)
#
# Examples:
#   # Forward :8080 -> 127.0.0.1:8081 (local port-to-port)
#   sudo ./setup_nft_port_forward_service.sh 8080 127.0.0.1 8081
#
#   # Forward :443 -> 10.0.0.25:8443 (LAN target)
#   sudo ./setup_nft_port_forward_service.sh 443 10.0.0.25 8443 tcp 0.0.0.0 1 1
#
# Logs:
#   sudo journalctl -u nft-port-forward-<listen_port>-<proto>.service -f
#
# To remove:
# sudo systemctl disable --now nft-port-forward-<listen_port>-<proto>.service
# sudo rm -f /etc/systemd/system/nft-port-forward-<listen_port>-<proto>.service
# sudo rm -f /usr/local/lib/port-forward/pf_<listen_port>_<proto>.nft \
#             /usr/local/lib/port-forward/apply-pf_<listen_port>_<proto>.sh \
#             /usr/local/lib/port-forward/remove-pf_<listen_port>_<proto>.sh
# sudo systemctl daemon-reload




set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: run with sudo/root." >&2
  exit 1
fi

LISTEN_PORT="${1:-}"
TARGET_HOST="${2:-}"
TARGET_PORT="${3:-}"
PROTO="${4:-tcp}"
LISTEN_ADDR="${5:-0.0.0.0}"
MASQ="${6:-1}"
REDIRECT_LOCAL_OUTPUT="${7:-1}"

if [[ -z "$LISTEN_PORT" || -z "$TARGET_HOST" || -z "$TARGET_PORT" ]]; then
  echo "Usage: sudo $0 <listen_port> <target_host> <target_port> [proto] [listen_addr] [masq] [redirect_local_output]" >&2
  exit 2
fi

if ! [[ "$LISTEN_PORT" =~ ^[0-9]+$ ]] || (( LISTEN_PORT < 1 || LISTEN_PORT > 65535 )); then
  echo "ERROR: invalid listen_port: $LISTEN_PORT" >&2
  exit 3
fi

if ! [[ "$TARGET_PORT" =~ ^[0-9]+$ ]] || (( TARGET_PORT < 1 || TARGET_PORT > 65535 )); then
  echo "ERROR: invalid target_port: $TARGET_PORT" >&2
  exit 3
fi

PROTO="${PROTO,,}"
if [[ "$PROTO" != "tcp" && "$PROTO" != "udp" ]]; then
  echo "ERROR: proto must be tcp or udp" >&2
  exit 4
fi

# Install deps (Ubuntu)
if ! command -v nft >/dev/null 2>&1; then
  apt-get update -y
  apt-get install -y nftables
fi

# Enable nftables service (safe even if you rely on our custom unit)
systemctl enable --now nftables >/dev/null 2>&1 || true

# Enable IPv4 forwarding (needed when forwarding to another host)
SYSCTL_CONF="/etc/sysctl.d/99-nft-port-forward.conf"
cat >"$SYSCTL_CONF" <<EOF
net.ipv4.ip_forward=1
EOF
sysctl -p "$SYSCTL_CONF" >/dev/null

NAME="pf_${LISTEN_PORT}_${PROTO}"
TABLE="ip ${NAME}"
SERVICE_NAME="nft-port-forward-${LISTEN_PORT}-${PROTO}.service"

BASE_DIR="/usr/local/lib/port-forward"
mkdir -p "$BASE_DIR"

NFT_FILE="${BASE_DIR}/${NAME}.nft"
APPLY_SH="${BASE_DIR}/apply-${NAME}.sh"
REMOVE_SH="${BASE_DIR}/remove-${NAME}.sh"
UNIT_FILE="/etc/systemd/system/${SERVICE_NAME}"

# Build match conditions
DADDR_MATCH=""
if [[ "$LISTEN_ADDR" != "0.0.0.0" ]]; then
  DADDR_MATCH="ip daddr ${LISTEN_ADDR} "
fi

# DNAT rules
PREROUTING_RULE="${DADDR_MATCH}${PROTO} dport ${LISTEN_PORT} dnat to ${TARGET_HOST}:${TARGET_PORT}"

# For locally-originated connections to the listen port on THIS machine:
# - Matching daddr type local catches traffic to 127.0.0.1 and this host's IPs.
OUTPUT_RULE="fib daddr type local ${DADDR_MATCH}${PROTO} dport ${LISTEN_PORT} dnat to ${TARGET_HOST}:${TARGET_PORT}"

# Masquerade (SNAT) only for DNATed flows (recommended for forwarding to another host)
MASQ_RULE=""
if [[ "$MASQ" == "1" ]]; then
  MASQ_RULE="ct status dnat masquerade"
fi

# Generate nft script (creates its own dedicated table; easy to remove)
cat >"$NFT_FILE" <<EOF
# Autogenerated by setup_nft_port_forward_service.sh
flush table ${TABLE} 2>/dev/null
table ${TABLE} {
  chain prerouting {
    type nat hook prerouting priority -100; policy accept;
    ${PREROUTING_RULE}
  }
EOF

if [[ "$REDIRECT_LOCAL_OUTPUT" == "1" ]]; then
  cat >>"$NFT_FILE" <<EOF
  chain output {
    type nat hook output priority -100; policy accept;
    ${OUTPUT_RULE}
  }
EOF
fi

cat >>"$NFT_FILE" <<EOF
  chain postrouting {
    type nat hook postrouting priority 100; policy accept;
EOF

if [[ -n "$MASQ_RULE" ]]; then
  cat >>"$NFT_FILE" <<EOF
    ${MASQ_RULE}
EOF
fi

cat >>"$NFT_FILE" <<EOF
  }
}
EOF

# Apply/remove helper scripts
cat >"$APPLY_SH" <<EOF
#!/usr/bin/env bash
set -euo pipefail
nft -f "$NFT_FILE"
EOF
chmod 0755 "$APPLY_SH"

cat >"$REMOVE_SH" <<EOF
#!/usr/bin/env bash
set -euo pipefail
nft delete table ${TABLE} 2>/dev/null || true
EOF
chmod 0755 "$REMOVE_SH"

# systemd unit
cat >"$UNIT_FILE" <<EOF
[Unit]
Description=NFTables port forward ${LISTEN_ADDR}:${LISTEN_PORT}/${PROTO} -> ${TARGET_HOST}:${TARGET_PORT} (masq=${MASQ})
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=${APPLY_SH}
ExecStop=${REMOVE_SH}

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now "$SERVICE_NAME"

# If UFW is active, open the port (best-effort)
if command -v ufw >/dev/null 2>&1; then
  if ufw status 2>/dev/null | grep -qi '^Status: active'; then
    ufw allow "${LISTEN_PORT}/${PROTO}" >/dev/null 2>&1 || true
    # Forwarded traffic may also require a routed allow; best-effort (especially if MASQ=0)
    ufw route allow proto "$PROTO" to "$TARGET_HOST" port "$TARGET_PORT" >/dev/null 2>&1 || true
  fi
fi

echo "Created:"
echo "  NFT rules : $NFT_FILE"
echo "  Service   : $UNIT_FILE"
echo
echo "Status:"
systemctl --no-pager --full status "$SERVICE_NAME" || true
echo
echo "Verify rules:"
echo "  sudo nft list table ${TABLE}"
echo
echo "Note: kernel NAT forwarding does NOT create a listening socket, so ss/netstat may not show ${LISTEN_PORT} as 'LISTEN'."
echo "Test:"
echo "  curl -v http://<this-host>:${LISTEN_PORT}   (or nc -vz <this-host> ${LISTEN_PORT})"
