-- Manual Cleanup Script for Oracle Migration Tables
-- Run this if tables become corrupted or need a fresh start.

DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE CONTACT CASCADE CONSTRAINTS;
DROP TABLE LEAD CASCADE CONSTRAINTS;
DROP TABLE OPPORTUNITY CASCADE CONSTRAINTS;

DROP TABLE ACCOUNT_TMP CASCADE CONSTRAINTS;
DROP TABLE CONTACT_TMP CASCADE CONSTRAINTS;
DROP TABLE LEAD_TMP CASCADE CONSTRAINTS;
DROP TABLE OPPORTUNITY_TMP CASCADE CONSTRAINTS;

COMMIT;
